"""Alarm-channel data distilled from the Bernina caQtDM alarm-overview panels.

Data-only module -- no EPICS/Qt import here. Every ``(name, pv, min, max)``
entry below is copied verbatim (channel name, PV, and the panel's own soft
min/max bounds -- these are *display-side* thresholds baked into the panel,
not the PV's own EPICS alarm limits) from the corresponding caQtDM ``.ui``
panel under ``/sf/bernina/config/src/caqtdm/alarms/``, extracted 2026-08-27.
Section labels for the Papamoll panels were cross-checked by majority vote
across all ``papamoll_alarms_overview_*.ui`` variants (several repeat the same
channel group under the same label) since a handful of source panels place
their caLabel section headers at coordinates that don't sit directly above
their data block -- see :mod:`eco.devices_general.alarms.panels` for the
`AlarmPanel`/`AlarmGroup` classes these feed into.

See also: :mod:`eco.devices_general.schneider_mcode_presets` for the same
"data table distilled from a device config document" convention.
"""

# Main "Alarms overview" panel: S_charts.json -> /sf/bernina/bin/alarms_caqtdm
# -> /sf/bernina/config/src/caqtdm/alarms/alarms.ui
MAIN_ALARMS_SECTIONS = [
    ('SwissFEL', [
        {"name": 'Electron_Beam', "pv": 'SARBD01-DBPM040:Q1', "min": 5, "max": 500},
        {"name": 'Photon_Shutter', "pv": 'SATFE10-OPSH040:PLC_OPEN', "min": 0.5, "max": 1.5},
        {"name": 'Bernina_Shutter', "pv": 'SAROP21-SBST114:PLC_VCS_CLOSE2', "min": -0.5, "max": 0.5},
        {"name": 'Pulse_Picker', "pv": 'SGE-CPCW-72-EVR0:FrontUnivOut15-Ena-SP', "min": 0.5, "max": 1.5},
        {"name": 'He_recovery_Air', "pv": 'IKA-GAMA:Luft_SF', "min": -0.5, "max": 20},
    ]),
    ('Laser', [
        {"name": 'Synch_DFreq', "pv": 'SLAAR-CSOC-DLL3-PYIOC:FREQ_DIFF', "min": -1, "max": 1},
        {"name": 'Synch_loop', "pv": 'SLAAR-CSOC-DLL3:FB-ENA', "min": 0.5, "max": 1.5},
        {"name": 'Oscillator_Bandwidth', "pv": 'SLAAR02-LSPC-OSC:FWHM', "min": 30, "max": 120},
        {"name": 'Pulse_Energy_mJ', "pv": 'SLAAR-LTIM02-EVR0:CALCS', "min": 20, "max": 27},
        {"name": 'Shutter', "pv": 'SLAAR21-LPSYS-ESB:TRANS_OPEN', "min": 0.5, "max": 1.5},
        {"name": 'Ang_X', "pv": 'SLAAR21-LCAM-CT1C1:ERR-X', "min": -1, "max": 1},
        {"name": 'Ang_Y', "pv": 'SLAAR21-LCAM-CT1C1:ERR-Y', "min": -1, "max": 1},
        {"name": 'Pos_X', "pv": 'SLAAR21-LCAM-CT1C2:ERR-X', "min": -2, "max": 2},
        {"name": 'Pos_Y', "pv": 'SLAAR21-LCAM-CT1C2:ERR-Y', "min": -2, "max": 2},
    ]),
    ('X-ray Pointing', [
        {"name": 'mon_mono_X', "pv": 'SAROP21-PBPS103:XPOS-ALL-HIST-M', "min": -0.005, "max": 0.005},
        {"name": 'mon_mono_Y', "pv": 'SAROP21-PBPS103:YPOS-ALL-HIST-M', "min": -0.005, "max": 0.005},
        {"name": 'mon_mono_I', "pv": 'SAROP21-PBPS103:AVG-INTENSITY', "min": 0.9, "max": 1.1},
        {"name": 'mon_opt_X', "pv": 'SAROP21-PBPS133:XPOS-ALL-HIST-M', "min": -0.005, "max": 0.005},
        {"name": 'mon_opt_Y', "pv": 'SAROP21-PBPS133:YPOS-ALL-HIST-M', "min": -0.005, "max": 0.005},
        {"name": 'mon_opt_I', "pv": 'SAROP21-PBPS133:AVG-INTENSITY', "min": 0.9, "max": 1.1},
        {"name": 'mon_kb_X', "pv": 'SARES21-PBPS141:XPOS-ALL-HIST-M', "min": -0.1, "max": 0.1},
        {"name": 'mon_kb_Y', "pv": 'SARES21-PBPS141:YPOS-ALL-HIST-M', "min": -0.1, "max": 0.1},
        {"name": 'mon_kb_I', "pv": 'SARES21-PBPS141:AVG-INTENSITY', "min": 0.9, "max": 1.2},
    ]),
    ('Timetool', [
        {"name": 'Edge_position', "pv": 'SLAAR21-GEN:SPECTT:PX-SIGMA.VALA', "min": 600, "max": 1400},
        {"name": 'Edge_amplitude', "pv": 'SLAAR21-GEN:SPECTT:MX-SIGMA.VALA', "min": 0.01, "max": 1},
        {"name": 'Arrival_time', "pv": 'SLAAR21-GEN:SPECTT-SIGMA.VALA', "min": -100, "max": 100},
    ]),
    ('Feedbacks', [
        {"name": 'Mono', "pv": 'SFBEB01-OMON-PBPS133:MSG', "min": None, "max": None},
        {"name": 'Laser', "pv": 'SFBEB01-LFIN-800NMTABLE1:MSG', "min": None, "max": None},
        {"name": 'Timetool', "pv": 'SFBEB01-LFIN-800NMTABLE2:MSG', "min": None, "max": None},
    ]),
]

# Papamoll (Coherent pump laser, SLG-L-COHERENT_PAPAMOLL) alarm-overview
# variants -- the two "Expert" buttons wired into alarms.ui, keyed the same
# as their source filename suffix
# (papamoll_alarms_overview_<key>.ui). Both share most sections (laser
# infrastructure: oscillator, amplifiers, timing, chillers, pointing) and
# differ mainly in the final "Pump Laser ..." section (1 um vs 510 nm stage).
PAPAMOLL_ALARMS_SECTIONS = {
    "26l_dean_1um_35fs": [
        ('Oscillator', [
            {"name": 'FWHM', "pv": 'SLAAR02-LSPC-OSC:FWHM', "min": 80, "max": 120},
            {"name": 'Centre', "pv": 'SLAAR02-LSPC-OSC:CENTRE', "min": 798, "max": 810},
            {"name": 'Base_height', "pv": 'SLAAR02-LSPC-OSC:BASE_HEIGHT', "min": 2300, "max": 2500},
            {"name": 'Amplitude', "pv": 'SLAAR02-LSPC-OSC:AMPLITUDE', "min": 3100, "max": 3200},
            {"name": 'Spec_ExpTime', "pv": 'SLAAR02-LSPC-OSC:EXPOSURE', "min": 50, "max": 220},
        ]),
        ('Amplifiers', [
            {"name": 'Revo01_Current(Amps)', "pv": 'SLAAR02-PLAS-REV02:CURRENT', "min": 16, "max": 19},
            {"name": 'Revo02_Current(Amps)', "pv": 'SLAAR02-PLAS-REV14:CURRENT', "min": 17, "max": 21},
            {"name": 'Revo03_Current(Amps)', "pv": 'SLAAR02-PLAS-REV15:CURRENT', "min": 17, "max": 22},
            {"name": 'Revo04_Current(Amps)', "pv": 'SLAAR02-PLAS-REV16:CURRENT', "min": 17, "max": 21},
            {"name": 'BWD_PD1', "pv": 'SLAAR02-PLAS-SDG01:BWD_PD1', "min": 45, "max": 100},
            {"name": 'BWD_PD2', "pv": 'SLAAR02-PLAS-SDG01:BWD_PD2', "min": 45, "max": 100},
            {"name": 'BWD_Level', "pv": 'SLAAR02-PLAS-SDG01:BWD_LVL', "min": 30, "max": 70},
            {"name": 'Pulse_Energy_mJ', "pv": 'SLAAR-LTIM02-EVR0:CALCS', "min": 21, "max": 25},
        ]),
        ('SDG_Trigger_Box', [
            {"name": 'Trigger_Source', "pv": 'SLAAR02-PLAS-SDG01:TRIG_SOURCE', "min": -0.5, "max": 0.5},
            {"name": 'Trigger_Freq', "pv": 'SLAAR02-PLAS-SDG01:TRIG_FREQ', "min": 95, "max": 105},
            {"name": 'Divider', "pv": 'SLAAR02-PLAS-SDG01:TRIG_DIV', "min": 0.9, "max": 1.1},
            {"name": 'Gating', "pv": 'SLAAR02-PLAS-SDG02:GATING', "min": 0.5, "max": 1.5},
            {"name": 'SDG1_DLY1', "pv": 'SLAAR02-PLAS-SDG01:CH1_DLY', "min": 3371.65, "max": 3371.85},
            {"name": 'SDG1_DLY2', "pv": 'SLAAR02-PLAS-SDG01:CH2_DLY', "min": 3454.05, "max": 3454.35},
            {"name": 'SDG2_DLY1', "pv": 'SLAAR02-PLAS-SDG02:CH1_DLY', "min": 89.15, "max": 89.35},
            {"name": 'SDG2_DLY2', "pv": 'SLAAR02-PLAS-SDG02:CH2_DLY', "min": 1499.95, "max": 1500.05},
        ]),
        ('Revo Water Temperature', [
            {"name": 'Revo01_in', "pv": 'SLAAR02-LI2C03_CH1:TEMP', "min": 24.2, "max": 24.5},
            {"name": 'Revo01_out', "pv": 'SLAAR02-LI2C03_CH2:TEMP', "min": 23.8, "max": 24},
            {"name": 'Revo02_in', "pv": 'SLAAR02-LI2C03_CH3:TEMP', "min": 25.3, "max": 25.5},
            {"name": 'Revo02_out', "pv": 'SLAAR02-LI2C03_CH4:TEMP', "min": 25.1, "max": 25.4},
            {"name": 'Revo03_in', "pv": 'SLAAR02-LI2C03_CH5:TEMP', "min": 22.9, "max": 23.1},
            {"name": 'Revo03_out', "pv": 'SLAAR02-LI2C03_CH6:TEMP', "min": 24.5, "max": 24.75},
            {"name": 'Revo04_in', "pv": 'SLAAR02-LI2C03_CH7:TEMP', "min": 23.6, "max": 24.8},
            {"name": 'Revo04_out', "pv": 'SLAAR02-LI2C03_CH8:TEMP', "min": 24.8, "max": 25.1},
        ]),
        ('Chillers_Temperature_Flow', [
            {"name": 'Chiller01_Temp', "pv": 'SLAAR02-LCHL-PS2:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller01_Flow', "pv": 'SLAAR02-LCHL-PS2:FLOW', "min": 12.4, "max": 12.7},
            {"name": 'Chiller02_Temp', "pv": 'SLAAR02-LCHL-PS14:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller02_Flow', "pv": 'SLAAR02-LCHL-PS14:FLOW', "min": 12.3, "max": 12.6},
            {"name": 'Chiller03_Temp', "pv": 'SLAAR02-LCHL-PS15:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller03_Flow', "pv": 'SLAAR02-LCHL-PS15:FLOW', "min": 10.3, "max": 10.6},
            {"name": 'Chiller04_Temp', "pv": 'SLAAR02-LCHL-PS16:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller04_Flow', "pv": 'SLAAR02-LCHL-PS16:FLOW', "min": 10.7, "max": 10.9},
        ]),
        ('Motors', [
            {"name": 'Switch_Mirror', "pv": 'SLAAR02-LMOT-M321:MOT.RBV', "min": 40, "max": 60},
            {"name": 'Lens_Telescope', "pv": 'SLAAR02-LMOT-M323:MOT.RBV', "min": 105, "max": 115},
        ]),
        ('LHX_800nm_Pointing/Width', [
            {"name": 'C281_dX-pos', "pv": 'SLAAR02-LPMO03-C281:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C281_X-wid', "pv": 'SLAAR02-LPMO03-C281:FIT-XWID', "min": 28, "max": 29},
            {"name": 'C281_dY-pos', "pv": 'SLAAR02-LPMO03-C281:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C281_Y-wid', "pv": 'SLAAR02-LPMO03-C281:FIT-YWID', "min": 26, "max": 27},
            {"name": 'C282_dX-pos', "pv": 'SLAAR02-LPMO04-C282:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C282_X-wid', "pv": 'SLAAR02-LPMO04-C282:FIT-XWID', "min": 84, "max": 85},
            {"name": 'C282_dY-pos', "pv": 'SLAAR02-LPMO04-C282:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C282_Y-wid', "pv": 'SLAAR02-LPMO04-C282:FIT-YWID', "min": 87, "max": 89},
            {"name": 'C321_dX-pos', "pv": 'SLAAR02-LPMO01-C321:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C321_X-wid', "pv": 'SLAAR02-LPMO01-C321:FIT-XWID', "min": 234, "max": 236},
            {"name": 'C321_dY-pos', "pv": 'SLAAR02-LPMO01-C321:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C321_Y-wid', "pv": 'SLAAR02-LPMO01-C321:FIT-YWID', "min": 255, "max": 256},
            {"name": 'C322_dX-pos', "pv": 'SLAAR02-LPMO02-C322:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C322_X-wid', "pv": 'SLAAR02-LPMO02-C322:FIT-XWID', "min": 14, "max": 16},
            {"name": 'C322_dY-pos', "pv": 'SLAAR02-LPMO02-C322:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C322_Y-wid', "pv": 'SLAAR02-LPMO02-C322:FIT-YWID', "min": 9, "max": 12},
        ]),
        ('ESB_Table1_800nm Pointing/Width', [
            {"name": 'CS843_dX-pos', "pv": 'SLAAR21-LCAM-CS843:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS843_X-wid', "pv": 'SLAAR21-LCAM-CS843:FIT-XWID', "min": 6, "max": 9},
            {"name": 'CS843_dY-pos', "pv": 'SLAAR21-LCAM-CS843:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS843_Y-wid', "pv": 'SLAAR21-LCAM-CS843:FIT-YWID', "min": 4, "max": 7},
            {"name": 'CS844_dX-pos', "pv": 'SLAAR21-LCAM-CS844:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS844_X-wid', "pv": 'SLAAR21-LCAM-CS844:FIT-XWID', "min": 218, "max": 222},
            {"name": 'CS844_dY-pos', "pv": 'SLAAR21-LCAM-CS844:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS844_Y-wid', "pv": 'SLAAR21-LCAM-CS844:FIT-YWID', "min": 240, "max": 245},
        ]),
        ('ESB_800nm Pointing Feedback', [
            {"name": 'Angle_Xerr', "pv": 'SLAAR21-LCAM-CT1C1:ERR-X', "min": -1, "max": 1},
            {"name": 'Angle_Yerr', "pv": 'SLAAR21-LCAM-CT1C1:ERR-Y', "min": -1, "max": 1},
            {"name": 'Position_Xerr', "pv": 'SLAAR21-LCAM-CT1C2:ERR-X', "min": -1.5, "max": 1.5},
            {"name": 'Position_Yerr', "pv": 'SLAAR21-LCAM-CT1C2:ERR-Y', "min": -1.5, "max": 1.5},
            {"name": 'FeedBack_RMS', "pv": 'SFBEB01-LFIN-800NMTABLE1:RMS_ERR_SUM', "min": 0, "max": 1.5},
            {"name": 'Piezo_Mirr1_X-ang', "pv": 'SLAAR21-LDIO-LAS6991:DAC01_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr1_Y-ang', "pv": 'SLAAR21-LDIO-LAS6991:DAC02_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr2_X-pos', "pv": 'SLAAR21-LDIO-LAS6991:DAC03_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr2_Y-pos', "pv": 'SLAAR21-LDIO-LAS6991:DAC04_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'StepMot_Mir1_X-ang', "pv": 'SLAAR21-LMOT-M553:MOT.VAL', "min": -15, "max": 15},
            {"name": 'StepMot_Mir1_Y-ang', "pv": 'SLAAR21-LMOT-M554:MOT.VAL', "min": -35, "max": 35},
            {"name": 'StepMot_Mir2_X-pos', "pv": 'SLAAR21-LMOT-M556:MOT.VAL', "min": -15, "max": 15},
            {"name": 'StepMot_Mir2_Y-pos', "pv": 'SLAAR21-LMOT-M557:MOT.VAL', "min": -35, "max": 35},
        ]),
        ('ESB_Temp-Hum-Pres', [
            {"name": 'Table-1_Temperature', "pv": 'SLAAR21-LI2C01_CH2:TEMP', "min": 23, "max": 25.5},
            {"name": 'Table-1_Humidity', "pv": 'SLAAR21-LI2C01_CH2:HUMIREL', "min": 30, "max": 45},
            {"name": 'Table-1_Pressure', "pv": 'SLAAR21-LI2C01_CH2:PRES', "min": 950, "max": 999},
            {"name": 'Table-2_Temperature', "pv": 'SLAAR21-LI2C01_CH5:TEMP', "min": 24, "max": 27.5},
            {"name": 'Table-2_Humidity', "pv": 'SLAAR21-LI2C01_CH5:HUMIREL', "min": 30, "max": 45},
            {"name": 'Table-2_Pressure', "pv": 'SLAAR21-LI2C01_CH5:PRES', "min": 950, "max": 999},
            {"name": 'Hutch_Temp', "pv": 'SARES20-CI2C_CH5:TEMP', "min": 23, "max": 26},
            {"name": 'Hutch_Hum', "pv": 'SARES20-CI2C_CH5:HUMIREL', "min": -0.1, "max": 45},
            {"name": 'Hutch_Pres', "pv": 'SARES20-CI2C_CH5:PRES', "min": 950, "max": 999},
        ]),
        ('ESB_Table2_800nm Pointing/Width', [
            {"name": 'CT1C1_dX-pos', "pv": 'SLAAR21-LCAM-CT1C1:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C1_X-wid', "pv": 'SLAAR21-LCAM-CT1C1:FIT-XWID', "min": 6, "max": 10},
            {"name": 'CT1C1_dY-pos', "pv": 'SLAAR21-LCAM-CT1C1:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C1_Y-wid', "pv": 'SLAAR21-LCAM-CT1C1:FIT-YWID', "min": 6, "max": 10},
            {"name": 'CT1C2_dX-pos', "pv": 'SLAAR21-LCAM-CT1C2:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C2_X-wid', "pv": 'SLAAR21-LCAM-CT1C2:FIT-XWID', "min": 250, "max": 254},
            {"name": 'CT1C2_dY-pos', "pv": 'SLAAR21-LCAM-CT1C2:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C2_Y-wid', "pv": 'SLAAR21-LCAM-CT1C2:FIT-YWID', "min": 293, "max": 297},
        ]),
        ('Pump Laser 1 um', [
            {"name": 'Lens_X', "pv": 'SARES20-XPS1:MOT_2', "min": -0.1, "max": 0.1},
            {"name": 'Lens_Y', "pv": 'SARES20-XPS1:MOT_3', "min": -0.1, "max": 0.1},
            {"name": 'Lens_Z', "pv": 'SARES20-XPS1:MOT_1', "min": 17.4, "max": 17.6},
            {"name": 'C561_dX-pos', "pv": 'SLAAR21-LCAM-CS842:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C561_dY-pos', "pv": 'SLAAR21-LCAM-CS842:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'Piezo_rx', "pv": 'SLAAR21-LDIO-LAS6991:DAC08_VOLTS', "min": 1, "max": 9},
            {"name": 'Piezo_ry', "pv": 'SLAAR21-LDIO-LAS6991:DAC07_VOLTS', "min": 1, "max": 9},
            {"name": 'Feedback', "pv": 'SLAAR21-LTIM01-EVR0:CALCW.A', "min": 0.9, "max": 1.1},
            {"name": 'I0_raw', "pv": 'SLAAR-LADC-WL009:ADC1_VAL', "min": 200000, "max": 220000},
            {"name": 'Pulse_energy', "pv": 'SLAAR21-L-BECKBS:PR1_CH0_VAL_GET', "min": 110, "max": 150},
            {"name": 'Spec_FWHM', "pv": 'SLAAR21-LSPC-PSENOUT:FWHM', "min": 40, "max": 50},
            {"name": 'Spec_Centre', "pv": 'SLAAR21-LSPC-PSENOUT:CENTRE', "min": 992, "max": 1000},
            {"name": 'Filter_wheel', "pv": 'SLAAR21-LMOT-ELL2:MOTRBV', "min": -1, "max": 1},
            {"name": 'HWP', "pv": 'SLAAR21-LMOT-ELL5:MOTRBV', "min": -1, "max": 45},
        ]),
        ('Timing_Synchronization', [
            {"name": 'Synch_DFreq', "pv": 'SLAAR-CSOC-DLL3-PYIOC:FREQ_DIFF', "min": -1, "max": 1},
            {"name": 'Synch_loop', "pv": 'SLAAR-CSOC-DLL3:FB-ENA', "min": 0.5, "max": 1.5},
            {"name": 'PD_current', "pv": 'SLAAR02-TLSY-EPL:PHOTOCURRMON', "min": 1.8, "max": 2.5},
            {"name": 'Dac_VVOA', "pv": 'SLAAR02-TLSY-EPL:GEN-DAC-5-4-SP', "min": 1.9, "max": 2.1},
            {"name": 'STD_fs', "pv": 'SLAAR-CSOC-DLL3-PYIOC:PHASE_DIFF_STD', "min": 5, "max": 20},
            {"name": 'Piezo_Voltage', "pv": 'SLAAR-LTIM02-EVR0:CALCI', "min": 10, "max": 80},
            {"name": 'Amp-CH1', "pv": 'SLAAR-CSOC-DLL3-PYIOC:AMP_CH1', "min": -1.1, "max": -0.1},
            {"name": 'Stage_motor', "pv": 'SLAAR02-LMOT-M261:MOT.RBV', "min": -5000, "max": 5000},
            {"name": 'Temperature', "pv": 'SLAAR02-LI2C01_CH2:TEMP', "min": 24, "max": 24.5},
            {"name": 'Humidity', "pv": 'SLAAR02-LI2C01_CH2:HUMIREL', "min": 20, "max": 45},
            {"name": 'Pressure', "pv": 'SLAAR02-LI2C01_CH2:PRES', "min": 950, "max": 999},
        ]),
    ],
    "26h_orr_510nm_100fs": [
        ('Oscillator', [
            {"name": 'FWHM', "pv": 'SLAAR02-LSPC-OSC:FWHM', "min": 29, "max": 33},
            {"name": 'Centre', "pv": 'SLAAR02-LSPC-OSC:CENTRE', "min": 786, "max": 790},
            {"name": 'Base_height', "pv": 'SLAAR02-LSPC-OSC:BASE_HEIGHT', "min": 2400, "max": 2600},
            {"name": 'Amplitude', "pv": 'SLAAR02-LSPC-OSC:AMPLITUDE', "min": 12400, "max": 12600},
            {"name": 'Spec_ExpTime', "pv": 'SLAAR02-LSPC-OSC:EXPOSURE', "min": 90, "max": 110},
        ]),
        ('Amplifiers', [
            {"name": 'Revo01_Current(Amps)', "pv": 'SLAAR02-PLAS-REV02:CURRENT', "min": 16, "max": 19},
            {"name": 'Revo02_Current(Amps)', "pv": 'SLAAR02-PLAS-REV14:CURRENT', "min": 17, "max": 21},
            {"name": 'Revo03_Current(Amps)', "pv": 'SLAAR02-PLAS-REV15:CURRENT', "min": 17, "max": 22},
            {"name": 'Revo04_Current(Amps)', "pv": 'SLAAR02-PLAS-REV16:CURRENT', "min": 17, "max": 21},
            {"name": 'BWD_PD1', "pv": 'SLAAR02-PLAS-SDG01:BWD_PD1', "min": 18, "max": 100},
            {"name": 'BWD_PD2', "pv": 'SLAAR02-PLAS-SDG01:BWD_PD2', "min": 18, "max": 100},
            {"name": 'BWD_Level', "pv": 'SLAAR02-PLAS-SDG01:BWD_LVL', "min": 9, "max": 70},
            {"name": 'Pulse_Energy_mJ', "pv": 'SLAAR-LTIM02-EVR0:CALCS', "min": 21, "max": 25},
        ]),
        ('SDG_Trigger_Box', [
            {"name": 'Trigger_Source', "pv": 'SLAAR02-PLAS-SDG01:TRIG_SOURCE', "min": -0.5, "max": 0.5},
            {"name": 'Trigger_Freq', "pv": 'SLAAR02-PLAS-SDG01:TRIG_FREQ', "min": 95, "max": 105},
            {"name": 'Divider', "pv": 'SLAAR02-PLAS-SDG01:TRIG_DIV', "min": 0.9, "max": 1.1},
            {"name": 'Gating', "pv": 'SLAAR02-PLAS-SDG02:GATING', "min": 0.5, "max": 1.5},
            {"name": 'SDG1_DLY1', "pv": 'SLAAR02-PLAS-SDG01:CH1_DLY', "min": 3392.15, "max": 3392.35},
            {"name": 'SDG1_DLY2', "pv": 'SLAAR02-PLAS-SDG01:CH2_DLY', "min": 3465.4, "max": 3465.6},
            {"name": 'SDG2_DLY1', "pv": 'SLAAR02-PLAS-SDG02:CH1_DLY', "min": 83.9, "max": 84.1},
            {"name": 'SDG2_DLY2', "pv": 'SLAAR02-PLAS-SDG02:CH2_DLY', "min": 1499.95, "max": 1500.05},
        ]),
        ('Revo Water Temperature', [
            {"name": 'Revo01_in', "pv": 'SLAAR02-LI2C03_CH1:TEMP', "min": 24.2, "max": 24.5},
            {"name": 'Revo01_out', "pv": 'SLAAR02-LI2C03_CH2:TEMP', "min": 23.8, "max": 24},
            {"name": 'Revo02_in', "pv": 'SLAAR02-LI2C03_CH3:TEMP', "min": 25.3, "max": 25.5},
            {"name": 'Revo02_out', "pv": 'SLAAR02-LI2C03_CH4:TEMP', "min": 25.1, "max": 25.4},
            {"name": 'Revo03_in', "pv": 'SLAAR02-LI2C03_CH5:TEMP', "min": 22.9, "max": 23.1},
            {"name": 'Revo03_out', "pv": 'SLAAR02-LI2C03_CH6:TEMP', "min": 24.5, "max": 24.75},
            {"name": 'Revo04_in', "pv": 'SLAAR02-LI2C03_CH7:TEMP', "min": 23.6, "max": 24.8},
            {"name": 'Revo04_out', "pv": 'SLAAR02-LI2C03_CH8:TEMP', "min": 24.8, "max": 25.1},
        ]),
        ('Chillers_Temperature_Flow', [
            {"name": 'Chiller01_Temp', "pv": 'SLAAR02-LCHL-PS2:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller01_Flow', "pv": 'SLAAR02-LCHL-PS2:FLOW', "min": 12.4, "max": 12.7},
            {"name": 'Chiller02_Temp', "pv": 'SLAAR02-LCHL-PS14:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller02_Flow', "pv": 'SLAAR02-LCHL-PS14:FLOW', "min": 12.3, "max": 12.6},
            {"name": 'Chiller03_Temp', "pv": 'SLAAR02-LCHL-PS15:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller03_Flow', "pv": 'SLAAR02-LCHL-PS15:FLOW', "min": 10.3, "max": 10.6},
            {"name": 'Chiller04_Temp', "pv": 'SLAAR02-LCHL-PS16:TEMP', "min": 19.9, "max": 20.1},
            {"name": 'Chiller04_Flow', "pv": 'SLAAR02-LCHL-PS16:FLOW', "min": 10.7, "max": 10.9},
        ]),
        ('Motors', [
            {"name": 'Switch_Mirror', "pv": 'SLAAR02-LMOT-M321:MOT.RBV', "min": 40, "max": 60},
            {"name": 'Lens_Telescope', "pv": 'SLAAR02-LMOT-M323:MOT.RBV', "min": 105, "max": 115},
        ]),
        ('LHX_800nm_Pointing/Width', [
            {"name": 'C281_dX-pos', "pv": 'SLAAR02-LPMO03-C281:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C281_X-wid', "pv": 'SLAAR02-LPMO03-C281:FIT-XWID', "min": 24.5, "max": 26},
            {"name": 'C281_dY-pos', "pv": 'SLAAR02-LPMO03-C281:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C281_Y-wid', "pv": 'SLAAR02-LPMO03-C281:FIT-YWID', "min": 26, "max": 27},
            {"name": 'C282_dX-pos', "pv": 'SLAAR02-LPMO04-C282:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C282_X-wid', "pv": 'SLAAR02-LPMO04-C282:FIT-XWID', "min": 205, "max": 207.5},
            {"name": 'C282_dY-pos', "pv": 'SLAAR02-LPMO04-C282:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C282_Y-wid', "pv": 'SLAAR02-LPMO04-C282:FIT-YWID', "min": 224, "max": 226.5},
            {"name": 'C321_dX-pos', "pv": 'SLAAR02-LPMO01-C321:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C321_X-wid', "pv": 'SLAAR02-LPMO01-C321:FIT-XWID', "min": 217, "max": 219},
            {"name": 'C321_dY-pos', "pv": 'SLAAR02-LPMO01-C321:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C321_Y-wid', "pv": 'SLAAR02-LPMO01-C321:FIT-YWID', "min": 234, "max": 236},
            {"name": 'C322_dX-pos', "pv": 'SLAAR02-LPMO02-C322:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C322_X-wid', "pv": 'SLAAR02-LPMO02-C322:FIT-XWID', "min": 14, "max": 16},
            {"name": 'C322_dY-pos', "pv": 'SLAAR02-LPMO02-C322:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'C322_Y-wid', "pv": 'SLAAR02-LPMO02-C322:FIT-YWID', "min": 9, "max": 12},
        ]),
        ('ESB_Table1_800nm Pointing/Width', [
            {"name": 'CS843_dX-pos', "pv": 'SLAAR21-LCAM-CS843:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS843_X-wid', "pv": 'SLAAR21-LCAM-CS843:FIT-XWID', "min": 6, "max": 9},
            {"name": 'CS843_dY-pos', "pv": 'SLAAR21-LCAM-CS843:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS843_Y-wid', "pv": 'SLAAR21-LCAM-CS843:FIT-YWID', "min": 3.5, "max": 5},
            {"name": 'CS844_dX-pos', "pv": 'SLAAR21-LCAM-CS844:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS844_X-wid', "pv": 'SLAAR21-LCAM-CS844:FIT-XWID', "min": 209, "max": 211},
            {"name": 'CS844_dY-pos', "pv": 'SLAAR21-LCAM-CS844:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS844_Y-wid', "pv": 'SLAAR21-LCAM-CS844:FIT-YWID', "min": 232, "max": 234},
        ]),
        ('ESB_800nm Pointing Feedback', [
            {"name": 'Angle_Xerr', "pv": 'SLAAR21-LCAM-CT1C1:ERR-X', "min": -1, "max": 1},
            {"name": 'Angle_Yerr', "pv": 'SLAAR21-LCAM-CT1C1:ERR-Y', "min": -1, "max": 1},
            {"name": 'Position_Xerr', "pv": 'SLAAR21-LCAM-CT1C2:ERR-X', "min": -1.5, "max": 1.5},
            {"name": 'Position_Yerr', "pv": 'SLAAR21-LCAM-CT1C2:ERR-Y', "min": -1.5, "max": 1.5},
            {"name": 'FeedBack_RMS', "pv": 'SFBEB01-LFIN-800NMTABLE1:RMS_ERR_SUM', "min": 0, "max": 1.5},
            {"name": 'Piezo_Mirr1_X-ang', "pv": 'SLAAR21-LDIO-LAS6991:DAC01_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr1_Y-ang', "pv": 'SLAAR21-LDIO-LAS6991:DAC02_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr2_X-pos', "pv": 'SLAAR21-LDIO-LAS6991:DAC03_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'Piezo_Mirr2_Y-pos', "pv": 'SLAAR21-LDIO-LAS6991:DAC04_VOLTS', "min": 0.5, "max": 9.5},
            {"name": 'StepMot_Mir1_X-ang', "pv": 'SLAAR21-LMOT-M553:MOT.VAL', "min": -15, "max": 15},
            {"name": 'StepMot_Mir1_Y-ang', "pv": 'SLAAR21-LMOT-M554:MOT.VAL', "min": -35, "max": 35},
            {"name": 'StepMot_Mir2_X-pos', "pv": 'SLAAR21-LMOT-M556:MOT.VAL', "min": -15, "max": 15},
            {"name": 'StepMot_Mir2_Y-pos', "pv": 'SLAAR21-LMOT-M557:MOT.VAL', "min": -35, "max": 35},
        ]),
        ('ESB_Temp-Hum-Pres', [
            {"name": 'Table-1_Temperature', "pv": 'SLAAR21-LI2C01_CH2:TEMP', "min": 23, "max": 25.5},
            {"name": 'Table-1_Humidity', "pv": 'SLAAR21-LI2C01_CH2:HUMIREL', "min": 30, "max": 45},
            {"name": 'Table-1_Pressure', "pv": 'SLAAR21-LI2C01_CH2:PRES', "min": 950, "max": 999},
            {"name": 'Table-2_Temperature', "pv": 'SLAAR21-LI2C01_CH5:TEMP', "min": 24, "max": 27.5},
            {"name": 'Table-2_Humidity', "pv": 'SLAAR21-LI2C01_CH5:HUMIREL', "min": 30, "max": 45},
            {"name": 'Table-2_Pressure', "pv": 'SLAAR21-LI2C01_CH5:PRES', "min": 950, "max": 999},
            {"name": 'Hutch_Temp', "pv": 'SARES20-CI2C_CH5:TEMP', "min": 23, "max": 26},
            {"name": 'Hutch_Hum', "pv": 'SARES20-CI2C_CH5:HUMIREL', "min": -0.1, "max": 45},
            {"name": 'Hutch_Pres', "pv": 'SARES20-CI2C_CH5:PRES', "min": 950, "max": 999},
        ]),
        ('ESB_Table2_800nm Pointing/Width', [
            {"name": 'CT1C1_dX-pos', "pv": 'SLAAR21-LCAM-CT1C1:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C1_X-wid', "pv": 'SLAAR21-LCAM-CT1C1:FIT-XWID', "min": 6, "max": 10},
            {"name": 'CT1C1_dY-pos', "pv": 'SLAAR21-LCAM-CT1C1:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C1_Y-wid', "pv": 'SLAAR21-LCAM-CT1C1:FIT-YWID', "min": 5, "max": 6.5},
            {"name": 'CT1C2_dX-pos', "pv": 'SLAAR21-LCAM-CT1C2:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C2_X-wid', "pv": 'SLAAR21-LCAM-CT1C2:FIT-XWID', "min": 248, "max": 251},
            {"name": 'CT1C2_dY-pos', "pv": 'SLAAR21-LCAM-CT1C2:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CT1C2_Y-wid', "pv": 'SLAAR21-LCAM-CT1C2:FIT-YWID', "min": 288, "max": 291},
        ]),
        ('Pump Laser 510 nm', [
            {"name": 'Lens_X', "pv": 'SARES20-XPS1:MOT_2', "min": -0.1, "max": 0.1},
            {"name": 'Lens_Y', "pv": 'SARES20-XPS1:MOT_3', "min": -0.1, "max": 0.1},
            {"name": 'Lens_Z', "pv": 'SARES20-XPS1:MOT_1', "min": -1, "max": 1},
            {"name": 'CS842_dX-pos', "pv": 'SLAAR21-LCAM-CS842:FIT-XPOS-DELTA', "min": -2, "max": 2},
            {"name": 'CS842_dY-pos', "pv": 'SLAAR21-LCAM-CS842:FIT-YPOS-DELTA', "min": -2, "max": 2},
            {"name": 'Piezo_rx', "pv": 'SLAAR21-LDIO-LAS6991:DAC10_VOLTS', "min": 1, "max": 9},
            {"name": 'Piezo_ry', "pv": 'SLAAR21-LDIO-LAS6991:DAC09_VOLTS', "min": 1, "max": 9},
            {"name": 'Feedback', "pv": 'SLAAR21-LTIM01-EVR0:CALCW.A', "min": 0.9, "max": 1.1},
            {"name": 'I0_raw', "pv": 'SLAAR-LADC-WL009:ADC1_VAL', "min": 100000, "max": 420000},
            {"name": 'Pulse_energy', "pv": 'SLAAR21-L-BECKBS:PR1_CH0_VAL_GET', "min": 110, "max": 150},
            {"name": 'Spec_FWHM', "pv": 'SLAAR21-LSPC-PSENOUT:FWHM', "min": 9, "max": 23},
            {"name": 'Spec_Centre', "pv": 'SLAAR21-LSPC-PSENOUT:CENTRE', "min": 509, "max": 535},
            {"name": 'HWP', "pv": 'SLAAR21-LMOT-ELL5:MOTRBV', "min": -1, "max": 45},
        ]),
        ('Timing_Synchronization', [
            {"name": 'Synch_DFreq', "pv": 'SLAAR-CSOC-DLL3-PYIOC:FREQ_DIFF', "min": -1, "max": 1},
            {"name": 'Synch_loop', "pv": 'SLAAR-CSOC-DLL3:FB-ENA', "min": 0.5, "max": 1.5},
            {"name": 'PD_current', "pv": 'SLAAR02-TLSY-EPL:PHOTOCURRMON', "min": 1.8, "max": 2.5},
            {"name": 'Dac_VVOA', "pv": 'SLAAR02-TLSY-EPL:GEN-DAC-5-4-SP', "min": 1.9, "max": 2.1},
            {"name": 'STD_fs', "pv": 'SLAAR-CSOC-DLL3-PYIOC:PHASE_DIFF_STD', "min": 5, "max": 20},
            {"name": 'Piezo_Voltage', "pv": 'SLAAR-LTIM02-EVR0:CALCI', "min": 10, "max": 80},
            {"name": 'Amp-CH1', "pv": 'SLAAR-CSOC-DLL3-PYIOC:AMP_CH1', "min": -1.1, "max": -0.1},
            {"name": 'Stage_motor', "pv": 'SLAAR02-LMOT-M261:MOT.RBV', "min": -5000, "max": 5000},
            {"name": 'Temperature', "pv": 'SLAAR02-LI2C01_CH2:TEMP', "min": 24, "max": 24.5},
            {"name": 'Humidity', "pv": 'SLAAR02-LI2C01_CH2:HUMIREL', "min": 20, "max": 45},
            {"name": 'Pressure', "pv": 'SLAAR02-LI2C01_CH2:PRES', "min": 950, "max": 999},
        ]),
    ],
}

# Human-readable label per Papamoll config key, for panel titles.
PAPAMOLL_LABELS = {
    "26l_dean_1um_35fs": "Papamoll -35 fs (1 \u00b5m pump, Dean/26L)",
    "26h_orr_510nm_100fs": "Papamoll -100 fs (510 nm pump, Orr/26H)",
}
